#!/bin/bash
set -e

FATFS_FILE=ff10c.zip
FATFS_URL="http://elm-chan.org/fsw/ff/$FATFS_FILE"

BASE_DIR=$(readlink -f `dirname "$0"`)
cd "$BASE_DIR"
git submodule update --init

mkdir -p dld lib

cd dld
if [ ! -e "$FATFS_FILE" ]; then
    wget "$FATFS_URL"
fi

cd ../lib

rm -rf fatfs
mkdir fatfs
cd fatfs
unzip -q "../../dld/$FATFS_FILE"
rm -- src/diskio.* src/ffconf.h
cp "../../dist/integer.h" src

cd "$BASE_DIR"

rm -rf system
mkdir system
cd system

while read pack; do
    cp -a "../lib/uos/packages/$pack/." .
done < ../lib/uos-packs
