#!/bin/bash
set -e

FATFS_FILE=ff10b.zip
FATFS_URL="http://elm-chan.org/fsw/ff/$FATFS_FILE"

cd $(dirname "$0")

mkdir -p dld lib

cd dld
if [ ! -e "$FATFS_FILE" ]; then
    wget "$FATFS_URL"
fi

cd ..

cd lib

rm -rf fatfs
mkdir fatfs
cd fatfs
unzip -q "../../dld/$FATFS_FILE"
rm -- src/diskio.* src/ffconf.h
cp "../../dist/integer.h" src

echo Success
